name: github-pages

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    name: build
    steps:
      #  Prepare
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Make out dir
        run: |
          mkdir out
        shell: bash
      - name: Rename README to index
        run: |
          mv ./docs/README.adoc ./docs/index.adoc
        shell: bash
      #  Build Asciidoc
      - name: Build HTML
        id: build-html
        uses: tonynv/asciidoctor-action@master
        with:
          program: "./scripts/docs/research/html.sh"
      # Build JMeter Reports
      - name: setup-jmeter
        run: |
          sudo apt-get update
          sudo apt install curl -y
          sudo apt install -y default-jdk
          sudo curl -O https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.3.tgz 
          sudo tar -xvf apache-jmeter-5.3.tgz
          # cd $GITHUB_WORKSPACE/apache-jmeter-5.3/lib && sudo curl -O https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.2.1/cmdrunner-2.2.1.jar
          # cd $GITHUB_WORKSPACE/apache-jmeter-5.3/lib/ext && sudo curl -O https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.6/jmeter-plugins-manager-1.6.jar
          # cd $GITHUB_WORKSPACE/apache-jmeter-5.3/lib && sudo java -jar cmdrunner-2.2.1.jar --tool org.jmeterplugins.repository.PluginManagerCMD install-all-except jpgc-hadoop,jpgc-oauth,ulp-jmeter-autocorrelator-plugin,ulp-jmeter-videostreaming-plugin,ulp-jmeter-gwt-plugin,tilln-iso8583
      - name: run-jmeter-test
        run: |
          FILES="./tests/benchmark/data/reports/*"
          for source_file in $FILES
          do
            source_file_filename_no_ext=${source_file%.*}
            out=${source_file_filename_no_ext##*/}
            mkdir ./out/${out}
            $GITHUB_WORKSPACE/apache-jmeter-5.3/bin/./jmeter.sh -g $source_file -o ./out/${out}
          done
        shell: bash
      # Deploy Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./out"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
