name: github-pages

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  adoc_build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    name: asciidoctor
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Rename README to index
        run: |
          mv ./docs/README.adoc ./docs/index.adoc
        shell: bash
      - name: Build HTML
        id: build-html
        uses: tonynv/asciidoctor-action@master
        with:
          program: "./scripts/docs/research/html.sh"
      - name: Build PDF
        id: build-pdf
        uses: tonynv/asciidoctor-action@master
        with:
          program: "./scripts/docs/research/pdf.sh"
      - name: Build Slides
        id: build-slides
        uses: tonynv/asciidoctor-action@master
        with:
          program: "./scripts/docs/slides/html.sh"
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./out"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
